import { Router, Request, Response } from 'express';
import axios from 'axios';
import { pool } from '../db';
import { authMiddleware, AuthRequest } from '../middlewares/auth';

const router = Router();

// ─── Asaas client ─────────────────────────────────────────────────────────────

const asaas = axios.create({
  baseURL: process.env.ASAAS_API_URL || 'https://sandbox.asaas.com/api/v3',
  headers: {
    'access_token': process.env.ASAAS_API_KEY || '',
    'Content-Type': 'application/json',
  },
});

// ─── Helper: find or create Asaas customer for a petcare client ───────────────

async function upsertAsaasCustomer(idCliente: number): Promise<string> {
  // Fetch client data
  const clientRes = await pool.query(
    'SELECT nome, email, telefone, cpf_cnpj FROM clientes WHERE id = $1',
    [idCliente],
  );
  if (clientRes.rows.length === 0) throw new Error('Cliente não encontrado.');
  const c = clientRes.rows[0];

  // Check if customer already registered in Asaas
  const existing = await pool.query(
    'SELECT asaas_customer_id FROM pagamentos WHERE id_agendamento IN (SELECT id FROM agendamentos WHERE id_cliente = $1) AND asaas_customer_id IS NOT NULL LIMIT 1',
    [idCliente],
  );
  if (existing.rows.length > 0 && existing.rows[0].asaas_customer_id) {
    return existing.rows[0].asaas_customer_id as string;
  }

  // Create new customer on Asaas
  const payload: Record<string, string> = {
    name: c.nome,
  };
  if (c.email)     payload.email    = c.email;
  if (c.telefone)  payload.phone    = c.telefone;
  if (c.cpf_cnpj)  payload.cpfCnpj  = c.cpf_cnpj;

  const { data } = await asaas.post('/customers', payload);
  return data.id as string;
}

// ─── POST /api/pagamentos  — create a charge for an appointment ───────────────

router.post('/', authMiddleware, async (req: AuthRequest, res: Response) => {
  const { id_agendamento, forma_pagamento = 'PIX' } = req.body as {
    id_agendamento: number;
    forma_pagamento?: 'PIX' | 'BOLETO' | 'CREDIT_CARD';
  };

  if (!id_agendamento) {
    res.status(400).json({ error: 'id_agendamento é obrigatório.' });
    return;
  }

  const formasValidas = ['PIX', 'BOLETO', 'CREDIT_CARD'];
  if (!formasValidas.includes(forma_pagamento)) {
    res.status(400).json({ error: 'forma_pagamento inválida. Use PIX, BOLETO ou CREDIT_CARD.' });
    return;
  }

  try {
    // Verify appointment exists and fetch service value
    const apptRes = await pool.query(
      `SELECT a.id, a.id_cliente, a.data_atendimento, a.status,
              s.valor, s.descricao
       FROM agendamentos a
       JOIN servicos s ON s.id = a.id_servico
       WHERE a.id = $1`,
      [id_agendamento],
    );
    if (apptRes.rows.length === 0) {
      res.status(404).json({ error: 'Agendamento não encontrado.' });
      return;
    }

    const appt = apptRes.rows[0];

    if (!appt.valor || Number(appt.valor) <= 0) {
      res.status(422).json({ error: 'O serviço não possui valor definido para cobrança.' });
      return;
    }

    // Check if a pending/active payment already exists for this appointment
    const dupCheck = await pool.query(
      `SELECT id, asaas_payment_id, status FROM pagamentos
       WHERE id_agendamento = $1 AND status NOT IN ('CANCELLED','REFUNDED','OVERDUE')`,
      [id_agendamento],
    );
    if (dupCheck.rows.length > 0) {
      res.status(409).json({
        error: 'Já existe uma cobrança ativa para este agendamento.',
        pagamento: dupCheck.rows[0],
      });
      return;
    }

    // Find or create Asaas customer
    const customerId = await upsertAsaasCustomer(appt.id_cliente);

    // Build Asaas payment payload
    const dueDate = new Date(appt.data_atendimento);
    dueDate.setDate(dueDate.getDate() + 1); // due the day of appointment
    const dueDateStr = dueDate.toISOString().split('T')[0];

    const asaasPayload: Record<string, unknown> = {
      customer:       customerId,
      billingType:    forma_pagamento,
      value:          Number(appt.valor),
      dueDate:        dueDateStr,
      description:    `PetCare – ${appt.descricao}`,
    };

    if (forma_pagamento === 'PIX') {
      asaasPayload.pixAddressKeyType = 'EVP'; // random key generated by Asaas
    }

    const { data: charge } = await asaas.post('/payments', asaasPayload);

    // Store payment record
    const insertRes = await pool.query(
      `INSERT INTO pagamentos
         (id_agendamento, asaas_customer_id, asaas_payment_id, valor, forma_pagamento, status,
          link_fatura)
       VALUES ($1,$2,$3,$4,$5,$6,$7)
       RETURNING *`,
      [
        id_agendamento,
        customerId,
        charge.id,
        appt.valor,
        forma_pagamento,
        charge.status,
        charge.invoiceUrl ?? null,
      ],
    );

    const pagamento = insertRes.rows[0];

    // If PIX, fetch QR code immediately
    if (forma_pagamento === 'PIX') {
      try {
        const { data: pixData } = await asaas.get(`/payments/${charge.id}/pixQrCode`);
        await pool.query(
          `UPDATE pagamentos SET pix_copia_cola = $1, pix_expiracao = $2 WHERE id = $3`,
          [pixData.payload ?? null, pixData.expirationDate ?? null, pagamento.id],
        );
        pagamento.pix_copia_cola = pixData.payload;
        pagamento.pix_expiracao  = pixData.expirationDate;
      } catch {
        // Non-fatal: PIX QR may take a moment to generate
      }
    }

    res.status(201).json(pagamento);
  } catch (err: unknown) {
    console.error('Asaas error:', err);
    if (axios.isAxiosError(err)) {
      const msg = err.response?.data?.errors?.[0]?.description ?? err.message;
      res.status(502).json({ error: `Asaas: ${msg}` });
      return;
    }
    const msg = err instanceof Error ? err.message : 'Erro interno.';
    res.status(500).json({ error: msg });
  }
});

// ─── GET /api/pagamentos/agendamento/:id  — get payment by appointment ────────

router.get('/agendamento/:id', authMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const result = await pool.query(
      'SELECT * FROM pagamentos WHERE id_agendamento = $1 ORDER BY criado_em DESC',
      [req.params.id],
    );
    res.json(result.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Erro interno.' });
  }
});

// ─── GET /api/pagamentos/:id  — get single payment + sync status from Asaas ──

router.get('/:id', authMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const dbRes = await pool.query('SELECT * FROM pagamentos WHERE id = $1', [req.params.id]);
    if (dbRes.rows.length === 0) {
      res.status(404).json({ error: 'Pagamento não encontrado.' });
      return;
    }

    const pag = dbRes.rows[0];

    // Sync status from Asaas
    try {
      const { data: charge } = await asaas.get(`/payments/${pag.asaas_payment_id}`);
      if (charge.status !== pag.status) {
        await pool.query(
          'UPDATE pagamentos SET status = $1, atualizado_em = NOW() WHERE id = $2',
          [charge.status, pag.id],
        );
        pag.status = charge.status;
      }

      // If PIX and no copia-cola yet, try again
      if (pag.forma_pagamento === 'PIX' && !pag.pix_copia_cola) {
        const { data: pixData } = await asaas.get(`/payments/${pag.asaas_payment_id}/pixQrCode`);
        await pool.query(
          'UPDATE pagamentos SET pix_copia_cola = $1, pix_expiracao = $2 WHERE id = $3',
          [pixData.payload ?? null, pixData.expirationDate ?? null, pag.id],
        );
        pag.pix_copia_cola = pixData.payload;
        pag.pix_expiracao  = pixData.expirationDate;
      }
    } catch {
      // Not fatal – return what we have in DB
    }

    res.json(pag);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Erro interno.' });
  }
});

// ─── DELETE /api/pagamentos/:id  — cancel a charge ────────────────────────────

router.delete('/:id', authMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const dbRes = await pool.query('SELECT * FROM pagamentos WHERE id = $1', [req.params.id]);
    if (dbRes.rows.length === 0) {
      res.status(404).json({ error: 'Pagamento não encontrado.' });
      return;
    }
    const pag = dbRes.rows[0];

    await asaas.delete(`/payments/${pag.asaas_payment_id}`);
    await pool.query(
      'UPDATE pagamentos SET status = $1, atualizado_em = NOW() WHERE id = $2',
      ['CANCELLED', pag.id],
    );

    res.json({ message: 'Cobrança cancelada.' });
  } catch (err: unknown) {
    console.error(err);
    if (axios.isAxiosError(err)) {
      const msg = err.response?.data?.errors?.[0]?.description ?? err.message;
      res.status(502).json({ error: `Asaas: ${msg}` });
      return;
    }
    res.status(500).json({ error: 'Erro interno.' });
  }
});

// ─── POST /api/pagamentos/webhook  — Asaas webhook (no auth) ─────────────────

router.post('/webhook', async (req: Request, res: Response) => {
  const event = req.body as {
    event: string;
    payment?: { id: string; status: string };
  };

  if (!event?.payment?.id) {
    res.status(400).json({ error: 'Payload inválido.' });
    return;
  }

  try {
    await pool.query(
      'UPDATE pagamentos SET status = $1, atualizado_em = NOW() WHERE asaas_payment_id = $2',
      [event.payment.status, event.payment.id],
    );
    res.json({ received: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Erro interno.' });
  }
});

export default router;
